-- issues 테이블 reason_code ENUM에 AUTO_RESOLVED 추가
ALTER TABLE issues
MODIFY COLUMN reason_code ENUM('DAMAGED', 'MOVE_LOCATION', 'WAITING_RETURN', 'STOCK_EXISTS', 'UNKNOWN', 'AUTO_RESOLVED') NOT NULL DEFAULT 'UNKNOWN';
